### PR TITLE
add: anchor has target attribute & img can be centered

### PR DESCRIPTION
**Pull request by tmchein**
Now the img tag can be centered by adding the attribute align="center" and also the anchor tag can use the target attribute.

### CODE REVIEW

**Comment by tmchein** [comment]
@crowlKats What do you think about this? (:

**Comment by crowlKats** [comment]
@tmchein what is going on with the css changes? diff is quite hard to read. If you want to change the css, please do so by changing the `main.scss` file in the style folder and running `make build`

**Comment by tmchein** [comment]
Oh I didnt know that, I will change the main.scss.
What I tried to do is to do img[align=center] so the user could center images with the attribute.

**Comment by tmchein** [comment]
@crowlKats Check back again pls (:

**Review by crowlKats — APPROVED** [review]
LGTM, thanks

**Pull request merged**
