### PR TITLE
feat: add footnote support

### PR DESCRIPTION
**Pull request by deer**
closes https://github.com/denoland/deno-gfm/issues/6

Someone created a marked extension late last year. I guess it works well enough. For the test I basically just took the example from upstream: https://raw.githubusercontent.com/bent10/marked-extensions/main/packages/footnote/test/fixtures/example.md

@hashrock, please take a look.

### CODE REVIEW

**Comment by hashrock** [comment]
Thank you!

image

I tried the Example, but the link doesn't seem to work. The backlink is working, so there might be interference with the existing renderer.

**Comment by deer** [comment]
Sorry @hashrock, that was possibly the worst PR I've ever created. The feature wasn't at all working 😭 

But on the positive side, it's now working and there are really good tests. Here's what's changed:
1. Add a bunch of line breaks in the markdown to make it super obvious that the page is moving around (or not). This was the primary problem.
2. Stop sanitizing certain attributes and classes necessary for the feature to actually work.
3. Include the extra necessary styles.
4. Copy the unit test from the [source](https://github.com/bent10/marked-extensions/blob/823ad1ef5c5d884f89fa4ba380b25c0d0814ddbe/packages/footnote/test/index.test.ts#L402) as the starting point and then modify it where necessary, instead of generating html from the markdown and assuming it's correct.
5. Add a lengthy server test to ensure styles and other stuff are working correctly.

**Comment by deer** [comment]
Waiting on https://github.com/denoland/deno-gfm/pull/99 so that the server test is cleaner and more useful.

**Comment by deer** [comment]
Hi @crowlKats, if you could jump in here again, that'd be appreciated.

**Review by crowlKats — APPROVED** [review]
LGTM

**Pull request merged**
