### PR TITLE
feat: add sanitize html option

### PR DESCRIPTION
**Pull request by lino-levan**
See #31 for context

### CODE REVIEW

**Comment by crowlKats** [comment]
i think it should rather have a opt-out name, like disableHtmlSanitization or something along the lines

**Comment by lino-levan** [comment]
It's currently opt-out, but I agree the name can be changed. Let me do that really quickly.

**Comment by lino-levan** [comment]
Thoughts @crowlKats?

**Comment by lino-levan** [comment]
@crowlKats PTAL 🙏

**Review by crowlKats — APPROVED** [review]
LGTM

**Pull request merged**
