### PR TITLE
chore: add basic md table with dollar sign test

### PR DESCRIPTION
**Pull request by deer**
closes https://github.com/denoland/deno-gfm/issues/65

@lionel-rowe @lino-levan, what do you think about this? I took the md from the issue and wrapped it with the boilerplate from the `README.md` file and everything is rendering correctly. Changing the spacing between the pipe and dollar sign had no effect.

So this PR is to just assert that the functionality works and won't break in the future.

### CODE REVIEW

**Comment by deer** [comment]
@hashrock, since you're so fast with reviewing these, what do you think about this one?

**Review by hashrock — APPROVED** [review]
LGTM!

**Comment by hashrock** [comment]
Ugh, it failed in CI.

https://github.com/denoland/deno-gfm/actions/runs/7571288796/job/20618506624#step:7:89

**Comment by deer** [comment]
A soft-conflict with the previous PR. I'll open a fix soon.

**Pull request merged**
