### PR TITLE
fix: use marked-mangle

### LINKED ISSUE #70: Dependency Deprecation Warning
Hello there! 👋

I noticed a deprecation warning in the module's dependency, `marked()`. The warning states that the `mangle` parameter is deprecated since version 5.0.0 and should not be used. Instead, it recommends using the npm package `marked-mangle`.

I kindly request the maintainers to consider updating the dependency, as suggested in the deprecation warning. This change will ensure the continued compatibility and stability of the module for Deno users.

### Warning

> marked(): mangle parameter is deprecated since version 5.0.0, should not be used and will be removed in the future. Instead use https://www.npmjs.com/package/marked-mangle.

### PR DESCRIPTION
**Pull request by lino-levan**
closes #70

### CODE REVIEW

**Comment by roberto-morado** [comment]
🚀

**Comment by hashrock** [comment]
the warning seems still appear on every rendering.
I think we might want to add marked-mangle to the dependencies to silence the warning. wdyt?

**Comment by lino-levan** [comment]
sure

**Comment by lino-levan** [comment]
Weird that I stopped getting the warning. Should be fixed now. Renaming the PR.

**Comment by lino-levan** [comment]
@hashrock any chance you could make a release?

**Pull request merged**
