### PR TITLE
feat: inline rendering

### LINKED ISSUE #27: Consider supporting inline markdown
Inline markdown could be useful for lightweight markup on blog post titles, and it could be implemented easily with Marked's `parseInline` function.

### PR DESCRIPTION
**Pull request by lino-levan**
Closes #27

### CODE REVIEW

**Comment by crowlKats** [comment]
Please add an example

**Comment by lino-levan** [comment]
no

**Comment by lino-levan** [comment]
I added an example.

**Review by crowlKats — APPROVED** [review]
LGTM

**Pull request merged**
